# -*- coding: utf-8 -*-
"""coral_bleaching_detection_gradcam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17S23ujDr0dUb28piH5NI8IpGr-wXbxJn
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import cv2

BASE_PATH = "/content/drive/MyDrive/coral_detection_model"
IMG_PATH = os.path.join(BASE_PATH, "All_Images")
LABELS_PATH = os.path.join(BASE_PATH, "labels.csv")

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

class CoralDataset(Dataset):
    def __init__(self, dataframe, img_dir, transform=None):
        self.df = dataframe
        self.img_dir = img_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img_name = self.df.iloc[idx, 0]
        label = int(self.df.iloc[idx, 1]-1)
        img_path = os.path.join(self.img_dir, img_name)
        image = Image.open(img_path).convert("RGB")
        if self.transform:
            image = self.transform(image)
        return image, label

labels_df = pd.read_csv(LABELS_PATH)
labels_df['image'] = labels_df['image'].str.strip()
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

dataset = CoralDataset(labels_df, IMG_PATH, transform=transform)
train_loader = DataLoader(dataset, batch_size=16, shuffle=True)

from torch.utils.data import Subset
train_loader = DataLoader(dataset, batch_size=16, shuffle=True)

import torch.nn as nn
import torch.optim as optim
from torchvision import models

model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
model.fc = nn.Linear(model.fc.in_features, 10)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

for epoch in range(3):
    model.train()
    running_loss = 0.0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

from torchvision import models
import cv2
import matplotlib.pyplot as plt
import numpy as np
import torch.nn.functional as F

class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer

        self.gradients = None
        self.activations = None

        self.hook_layers()

    def hook_layers(self):
        def forward_hook(module, input, output):
            self.activations = output.detach()

        def backward_hook(module, grad_input, grad_output):
            self.gradients = grad_output[0].detach()

        self.target_layer.register_forward_hook(forward_hook)
        self.target_layer.register_backward_hook(backward_hook)

    def generate(self, input_tensor, class_idx=None):
        self.model.eval()
        output = self.model(input_tensor)

        if class_idx is None:
            class_idx = output.argmax().item()

        self.model.zero_grad()
        one_hot = torch.zeros((1, output.size()[-1]), dtype=torch.float32).to(input_tensor.device)
        one_hot[0][class_idx] = 1
        output.backward(gradient=one_hot)

        weights = self.gradients.mean(dim=(2, 3), keepdim=True)
        grad_cam_map = (weights * self.activations).sum(dim=1, keepdim=True)
        grad_cam_map = F.relu(grad_cam_map)

        grad_cam_map = F.interpolate(grad_cam_map, size=(224, 224), mode='bilinear', align_corners=False)
        grad_cam_map = grad_cam_map.squeeze().cpu().numpy()
        grad_cam_map = (grad_cam_map - grad_cam_map.min()) / (grad_cam_map.max() - grad_cam_map.min() + 1e-8)

        return grad_cam_map

idx = 10

img_tensor, true_label = small_dataset[idx]
img_tensor = img_tensor.unsqueeze(0).to(device)

target_layer = model.layer4[1].conv2

gradcam = GradCAM(model, target_layer)
cam_map = gradcam.generate(img_tensor)

img_np = img_tensor.squeeze().permute(1, 2, 0).cpu().numpy()
img_np = (img_np - img_np.min()) / (img_np.max() - img_np.min())

heatmap = cv2.applyColorMap(np.uint8(255 * cam_map), cv2.COLORMAP_JET)
heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
heatmap = heatmap / 255.0

overlay = 0.4 * heatmap + 0.6 * img_np

plt.figure(figsize=(10, 4))
plt.subplot(1, 3, 1)
plt.title("Original Image")
plt.imshow(img_np)
plt.axis('off')

plt.subplot(1, 3, 2)
plt.title("Grad-CAM Heatmap")
plt.imshow(cam_map, cmap='jet')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.title("Overlay")
plt.imshow(overlay)
plt.axis('off')

plt.tight_layout()
plt.show()

!pip install gradio --quiet

import gradio as gr

def predict_with_heatmap(uploaded_img):
    try:
        print("Starting prediction...")
        img = Image.open(uploaded_img).convert("RGB")
        print("Image loaded.")

        transformed = transform(img).unsqueeze(0).to(device)
        print("Image transformed.")
        model.eval()
        output = model(transformed)
        pred_class = output.argmax(dim=1).item()
        print(f"Predicted class: {pred_class}")

        cam_map = gradcam.generate(transformed)
        print("Grad-CAM generated.")

        img_np = transformed.squeeze().permute(1, 2, 0).cpu().numpy()
        img_np = (img_np - img_np.min()) / (img_np.max() - img_np.min())

        heatmap = cv2.applyColorMap(np.uint8(255 * cam_map), cv2.COLORMAP_JET)
        heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB) / 255.0
        overlay = 0.4 * heatmap + 0.6 * img_np
        print("Overlay generated.")

        cam_map_img = np.uint8(255 * cam_map)
        cam_map_img = cv2.cvtColor(cam_map_img, cv2.COLOR_GRAY2RGB)  
        overlay = np.clip(overlay, 0, 1)
        overlay_img = (overlay * 255).astype(np.uint8)
        
        img_np_disp = (img_np * 255).astype(np.uint8)

        return (pred_class, img_np_disp, cam_map_img, overlay_img)


    except Exception as e:
        print("Error:", e)
        return "Error", None, None, None

interface = gr.Interface(
    fn=predict_with_heatmap,
    inputs=gr.Image(type="filepath", label="Upload Coral Image"),
    outputs=[
        gr.Label(num_top_classes=1, label="Predicted Bleaching Score (0-10)"),
        gr.Image(label="Original Image"),
        gr.Image(label="Grad-CAM Heatmap"),
        gr.Image(label="Overlay"),
    ],
    title="Coral Bleaching Detector",
    description="Upload a coral image to detect bleaching severity and view model explanation (Grad-CAM)."
)

interface.launch(debug=True)
